2017-03-11 19:08:28,413 [Thread-2:8408] [django.request:182] [base:get_response] [WARNING]- Not Found: /admin/blog/article/1/change/
2017-03-11 23:25:11,049 [Thread-2:3720] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view blog.views.index didn't return an HttpResponse object. It returned None instead.
2017-03-12 00:02:14,619 [Thread-13:8572] [django.request:182] [base:get_response] [WARNING]- Not Found: /index.html
2017-03-16 23:08:13,639 [Thread-65:7868] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\backends\mysql\base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 852, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 1053, in _read_query_result
    result.read()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 1336, in read
    first_packet = self.connection._read_packet()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 1010, in _read_packet
    packet.check_error()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\contrib\admin\options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "c:\program files\python35\Lib\contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\contrib\admin\options.py", line 1378, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\contrib\admin\options.py", line 991, in save_model
    obj.save()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\backends\mysql\base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 852, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 1053, in _read_query_result
    result.read()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 1336, in read
    first_packet = self.connection._read_packet()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 1010, in _read_packet
    packet.check_error()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2017-03-16 23:18:44,245 [Thread-54:8016] [django.request:182] [base:get_response] [WARNING]- Not Found: /index.html
2017-03-17 01:53:45,630 [Thread-3:9448] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /archive/
Traceback (most recent call last):
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view blog.views.archive didn't return an HttpResponse object. It returned None instead.
2017-03-17 01:59:26,144 [Thread-2:9528] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /archive/
Traceback (most recent call last):
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view blog.views.archive didn't return an HttpResponse object. It returned None instead.
2017-03-17 02:21:17,598 [Thread-26:6272] [django.request:182] [base:get_response] [WARNING]- Not Found: /archive/index.html
2017-03-19 20:04:35,270 [Thread-8:6368] [django.request:182] [base:get_response] [WARNING]- Not Found: /archive/index.html
2017-03-19 21:34:30,166 [Thread-2:4552] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /archive/
Traceback (most recent call last):
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\WorkSpace\Python\my_blog\blog\views.py", line 84, in archive
    return render(request,'archive.html',locals())
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\base.py", line 204, in render
    with context.bind_template(self):
  File "c:\program files\python35\Lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\context.py", line 260, in bind_template
    updates.update(processor(self.request))
  File "E:\WorkSpace\Python\my_blog\blog\views.py", line 25, in global_setting
    comment_count_list = Comment.objects.values('article').annotate(comment_count=Count('article').order_by('-comment_count'))
AttributeError: 'Count' object has no attribute 'order_by'
2017-03-19 21:36:51,540 [Thread-2:10504] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\WorkSpace\Python\my_blog\blog\views.py", line 67, in index
    return render(request, 'index.html', locals())
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\base.py", line 204, in render
    with context.bind_template(self):
  File "c:\program files\python35\Lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\context.py", line 260, in bind_template
    updates.update(processor(self.request))
  File "E:\WorkSpace\Python\my_blog\blog\views.py", line 25, in global_setting
    comment_count_list = Comment.objects.values('article').annotate(comment_count=Count('article').order_by('-comment_count'))
AttributeError: 'Count' object has no attribute 'order_by'
2017-03-19 21:39:01,754 [Thread-2:10928] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\WorkSpace\Python\my_blog\blog\views.py", line 67, in index
    return render(request, 'index.html', locals())
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\base.py", line 204, in render
    with context.bind_template(self):
  File "c:\program files\python35\Lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\context.py", line 260, in bind_template
    updates.update(processor(self.request))
  File "E:\WorkSpace\Python\my_blog\blog\views.py", line 26, in global_setting
    print(comment_count_list)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\query.py", line 234, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\query.py", line 258, in __iter__
    self._fetch_all()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\query.py", line 112, in __iter__
    for row in compiler.results_iter():
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 802, in results_iter
    results = self.execute_sql(MULTI)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 837, in execute_sql
    sql, params = self.as_sql()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 382, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 48, in pre_sql_setup
    self.setup_query()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 39, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 228, in get_select
    ret.append((col, self.compile(col, select_format=True), alias))
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 368, in compile
    return node.output_field.select_format(self, sql, params)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\expressions.py", line 228, in output_field
    if self._output_field_or_none is None:
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\expressions.py", line 240, in _output_field_or_none
    if self._output_field is None:
AttributeError: 'OrderBy' object has no attribute '_output_field'
2017-03-19 21:42:26,687 [Thread-2:3656] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\WorkSpace\Python\my_blog\blog\views.py", line 68, in index
    return render(request, 'index.html', locals())
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\base.py", line 204, in render
    with context.bind_template(self):
  File "c:\program files\python35\Lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\template\context.py", line 260, in bind_template
    updates.update(processor(self.request))
  File "E:\WorkSpace\Python\my_blog\blog\views.py", line 27, in global_setting
    print(comment_count_list)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\query.py", line 234, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\query.py", line 258, in __iter__
    self._fetch_all()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\query.py", line 112, in __iter__
    for row in compiler.results_iter():
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 802, in results_iter
    results = self.execute_sql(MULTI)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 837, in execute_sql
    sql, params = self.as_sql()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 382, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 48, in pre_sql_setup
    self.setup_query()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 39, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 228, in get_select
    ret.append((col, self.compile(col, select_format=True), alias))
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\sql\compiler.py", line 368, in compile
    return node.output_field.select_format(self, sql, params)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\expressions.py", line 228, in output_field
    if self._output_field_or_none is None:
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\WorkSpace\django_basic_env\lib\site-packages\django\db\models\expressions.py", line 240, in _output_field_or_none
    if self._output_field is None:
AttributeError: 'OrderBy' object has no attribute '_output_field'
2017-03-19 17:51:37,885 [Thread-27:123145399169024] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 17:51:38,076 [Thread-28:123145399169024] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 18:02:35,436 [Thread-40:123145399169024] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 18:02:35,563 [Thread-41:123145399169024] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 18:18:41,868 [Thread-60:123145399169024] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 18:18:42,000 [Thread-61:123145399169024] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 18:19:29,482 [Thread-86:123145399169024] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 18:19:29,598 [Thread-87:123145399169024] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 18:35:53,949 [Thread-88:123145399169024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 117, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 487, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 485, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 601, in compile_filter
    return FilterExpression(token, self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 695, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 607, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'month_to_upper'
2017-03-19 18:44:39,008 [Thread-93:123145399169024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'myfilter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 117, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2017-03-19 18:47:05,723 [Thread-123:123145399169024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'myfilter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 117, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2017-03-19 18:49:12,135 [Thread-124:123145399169024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'myfilter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 117, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2017-03-19 18:52:07,900 [Thread-126:123145399169024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'myfilter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 117, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2017-03-19 18:53:53,567 [Thread-129:123145399169024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'myfilter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 117, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2017-03-19 18:59:34,078 [Thread-154:123145399169024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'myfilter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 117, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2017-03-19 19:04:30,075 [Thread-156:123145404424192] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'templatetags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 117, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1183, in load
    lib = find_library(parser, name)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'templatetags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2017-03-19 19:05:46,012 [Thread-158:123145404424192] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'myfilter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 117, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1183, in load
    lib = find_library(parser, name)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
2017-03-19 19:12:45,555 [Thread-26:123145565622272] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:12:45,682 [Thread-27:123145565622272] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:16:58,761 [Thread-3:123145373061120] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:16:58,912 [Thread-4:123145367805952] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:19:55,291 [Thread-6:123145373061120] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:19:55,423 [Thread-7:123145367805952] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:32:19,592 [Thread-36:123145367805952] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:32:19,744 [Thread-37:123145367805952] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:33:19,462 [Thread-44:123145373061120] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:42:12,819 [Thread-46:123145373061120] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:42:13,008 [Thread-47:123145367805952] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:42:25,107 [Thread-49:123145373061120] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:42:25,256 [Thread-50:123145367805952] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 19:45:02,362 [Thread-2:123145329725440] [django.request:182] [base:get_response] [WARNING]- Not Found: /test
2017-03-19 20:07:00,302 [Thread-12:123145415954432] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /test/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 122, in test
    return  render(request,'test.html')
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 885, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 601, in compile_filter
    return FilterExpression(token, self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 701, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(100)' from 'range(100)'
2017-03-19 20:09:48,556 [Thread-43:123145415954432] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:09:48,644 [Thread-44:123145415954432] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:16:23,368 [Thread-57:123145421209600] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:16:23,491 [Thread-58:123145426464768] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:17:04,291 [Thread-63:123145421209600] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:17:04,405 [Thread-64:123145426464768] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:17:17,193 [Thread-68:123145421209600] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:17:17,259 [Thread-69:123145415954432] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:32:46,202 [Thread-26:123145495650304] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:32:46,660 [Thread-27:123145495650304] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:46:26,262 [Thread-4:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:46:26,379 [Thread-5:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:51:25,551 [Thread-7:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:51:25,665 [Thread-8:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:53:35,228 [Thread-10:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:53:35,337 [Thread-11:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:54:29,238 [Thread-13:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:54:29,349 [Thread-14:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:54:37,897 [Thread-17:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:54:37,972 [Thread-18:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:55:24,761 [Thread-25:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:56:36,084 [Thread-39:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 20:56:36,195 [Thread-40:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 21:00:14,978 [Thread-42:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 21:00:15,099 [Thread-43:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 21:01:18,650 [Thread-46:123145566695424] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 21:01:18,701 [Thread-47:123145571950592] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 21:01:37,159 [Thread-51:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-19 21:01:37,336 [Thread-52:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 02:55:13,990 [Thread-65:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 02:55:14,135 [Thread-66:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 02:56:00,603 [Thread-79:123145556185088] [django.request:182] [base:get_response] [WARNING]- Not Found: /index.html
2017-03-20 03:13:47,964 [Thread-144:123145561440256] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 03:13:48,083 [Thread-145:123145566695424] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 03:14:32,692 [Thread-150:123145561440256] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 03:14:32,813 [Thread-151:123145566695424] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:44:04,132 [Thread-25:123145350651904] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-20 16:44:24,935 [Thread-28:123145350651904] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:44:25,024 [Thread-29:123145350651904] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:56:03,633 [Thread-3:123145475178496] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:56:03,675 [Thread-4:123145480433664] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:57:17,560 [Thread-9:123145475178496] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:57:17,653 [Thread-10:123145480433664] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:58:58,674 [Thread-3:123145516957696] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:58:58,763 [Thread-4:123145522212864] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:59:04,702 [Thread-10:123145516957696] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:59:04,737 [Thread-11:123145522212864] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:59:37,488 [Thread-17:123145511702528] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 16:59:37,523 [Thread-18:123145511702528] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 17:05:49,155 [Thread-3:123145429319680] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 17:05:49,258 [Thread-4:123145434574848] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 17:08:03,193 [Thread-3:123145407918080] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 17:08:03,286 [Thread-4:123145413173248] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 17:09:09,423 [Thread-3:123145472819200] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 17:09:09,506 [Thread-4:123145478074368] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/images/default.jpg
2017-03-20 18:45:49,255 [Thread-11:123145461948416] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 508, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 157, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 1042, in do_if
    nodelist = parser.parse(('endif',))
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 510, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 566, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until]),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 118: 'endblock', expected 'endif'. Did you forget to register or load this tag?
2017-03-21 13:18:15,537 [Thread-25:123145478131712] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-21 13:19:11,937 [Thread-33:123145478131712] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/css/reglogin.css
2017-03-21 13:19:16,458 [Thread-34:123145478131712] [django.request:182] [base:get_response] [WARNING]- Not Found: /reg/ }
2017-03-21 18:31:59,149 [Thread-50:123145393381376] [django.request:182] [base:get_response] [WARNING]- Not Found: /reg/ }
2017-03-21 18:32:07,390 [Thread-53:123145403891712] [django.request:182] [base:get_response] [WARNING]- Not Found: /reg/css/reglogin.css
2017-03-21 18:33:44,302 [Thread-57:123145393381376] [django.request:182] [base:get_response] [WARNING]- Not Found: /reg/ }
2017-03-21 18:34:24,983 [Thread-64:123145393381376] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/css/reglogin.css
2017-03-21 18:34:39,485 [Thread-66:123145398636544] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/css/reglogin.css
2017-03-21 18:34:47,336 [Thread-69:123145393381376] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/css/reglogin.css
2017-03-21 18:35:30,757 [Thread-74:123145393381376] [django.request:182] [base:get_response] [WARNING]- Not Found: /reg/css/reglogin.css
2017-03-21 18:36:49,355 [Thread-76:123145393381376] [django.request:182] [base:get_response] [WARNING]- Not Found: /reg/css/reglogin.css
2017-03-21 19:02:21,738 [Thread-91:123145393381376] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/comment_post
2017-03-21 19:04:12,149 [Thread-96:123145393381376] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/comment_post
2017-03-21 19:04:20,018 [Thread-99:123145393381376] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article/
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 507, in render
    current_app=current_app)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'my_blog.comment/post' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 147, in article
    return render(request,'article.html',locals())
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'comment/post' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-21 19:10:45,299 [Thread-3:123145528995840] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF cookie not set.): /comment_post
2017-03-21 19:23:54,121 [Thread-7:123145528995840] [django.request:182] [base:get_response] [WARNING]- Not Found: /article/index.html
2017-03-22 05:44:08,675 [Thread-64:123145557336064] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/css/reglogin.css
2017-03-22 18:57:14,285 [Thread-25:123145474678784] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-22 19:12:03,554 [Thread-2:123145364422656] [django.request:182] [base:get_response] [WARNING]- Not Found: /test
2017-03-22 19:13:01,193 [Thread-2:123145314320384] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /test
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: test() takes 0 positional arguments but 1 was given
2017-03-22 19:13:36,726 [Thread-2:123145378168832] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /test
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 245, in test
    user='admin')
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in create
    obj = self.model(**kwargs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/base.py", line 439, in __init__
    setattr(self, field.name, rel_obj)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "'admin'": "Comment.user" must be a "User" instance.
2017-03-22 19:14:46,466 [Thread-2:123145533476864] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /test
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 245, in test
    user=User.username)
AttributeError: type object 'User' has no attribute 'username'
2017-03-22 19:17:06,606 [Thread-2:123145560096768] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /test
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 246, in test
    user=1)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in create
    obj = self.model(**kwargs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/base.py", line 439, in __init__
    setattr(self, field.name, rel_obj)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "1": "Comment.user" must be a "User" instance.
2017-03-22 19:17:39,825 [Thread-5:123145560096768] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /test
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jiangzhuolin/workspace/my_blog/blog/views.py", line 246, in test
    user=1)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/query.py", line 399, in create
    obj = self.model(**kwargs)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/base.py", line 439, in __init__
    setattr(self, field.name, rel_obj)
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "1": "Comment.user" must be a "User" instance.
2017-03-22 19:20:51,882 [Thread-2:123145573703680] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /test
Traceback (most recent call last):
  File "/workspace/python/django_blog_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view blog.views.test didn't return an HttpResponse object. It returned None instead.
2017-03-22 19:38:13,352 [Thread-11:123145476997120] [django.request:182] [base:get_response] [WARNING]- Not Found: /reg/css/reglogin.css
2017-03-22 19:55:55,206 [Thread-23:123145482252288] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/css/reglogin.css
2017-03-22 20:08:02,919 [Thread-26:123145476997120] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /reg/
2017-03-22 20:08:29,669 [Thread-27:123145476997120] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /reg/
